export const PERMISOS = {
  VER_DASHBOARD: 'VER_DASHBOARD',
  GESTIONAR_EMPLEADOS: 'GESTIONAR_EMPLEADOS',
  GESTIONAR_DOCUMENTOS: 'GESTIONAR_DOCUMENTOS',
  GESTIONAR_LOTES: 'GESTIONAR_LOTES',
  GESTIONAR_SOLICITUDES: 'GESTIONAR_SOLICITUDES',
  VER_AUDITORIA: 'VER_AUDITORIA',
  GESTIONAR_CONFIGURACION: 'GESTIONAR_CONFIGURACION',
  GESTIONAR_USUARIOS: 'GESTIONAR_USUARIOS',
  GESTIONAR_CALENDARIO: 'GESTIONAR_CALENDARIO',
  GESTIONAR_EVALUACIONES: 'GESTIONAR_EVALUACIONES',
  GESTIONAR_FORMULARIOS: 'GESTIONAR_FORMULARIOS',
  GESTIONAR_AUSENCIAS: 'GESTIONAR_AUSENCIAS',
  PUBLICAR_FEED: 'PUBLICAR_FEED',
} as const

export type Permiso = typeof PERMISOS[keyof typeof PERMISOS]

export const TODOS_LOS_PERMISOS = Object.values(PERMISOS) as Permiso[]

export const LABELS_PERMISOS: Record<Permiso, string> = {
  VER_DASHBOARD: 'Ver dashboard',
  GESTIONAR_EMPLEADOS: 'Gestionar empleados',
  GESTIONAR_DOCUMENTOS: 'Gestionar documentos',
  GESTIONAR_LOTES: 'Gestionar recibos de sueldo',
  GESTIONAR_SOLICITUDES: 'Gestionar solicitudes',
  VER_AUDITORIA: 'Ver auditoría',
  GESTIONAR_CONFIGURACION: 'Gestionar configuración',
  GESTIONAR_USUARIOS: 'Gestionar usuarios y roles',
  GESTIONAR_CALENDARIO: 'Gestionar calendario',
  GESTIONAR_EVALUACIONES: 'Gestionar evaluaciones de desempeño',
  GESTIONAR_FORMULARIOS: 'Gestionar formularios',
  GESTIONAR_AUSENCIAS: 'Gestionar ausencias y vacaciones',
  PUBLICAR_FEED: 'Publicar en el portal interno',
}
