IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'TipoDocumento' AND COLUMN_NAME = 'protegido')
BEGIN
  ALTER TABLE [TipoDocumento] ADD [protegido] BIT NOT NULL DEFAULT 0
END
